### ISSUE TITLE
Enum cases with associated values cannot be marked potentially unavailable with '@available'

### ISSUE THREAD

**Issue by fadielse** [qiscus/qiscus-multichannel-widget-ios#1]
Hi 
I'm trying to integration and got an error  

- file _CocoaMQTTTypes_ line 67
- app deployment version 10.0
- xcode 13.1

thanks for the response

**Comment by ariefnurputranto** [comment]
Hi @fadielse , 

Thanks for your report, I'll be releasing to support XCode 13++ today. I will tell you soon

**Comment by ariefnurputranto** [comment]
hi @fadielse ,

We have released to support XCode 13 in version 2.0.1

Thanks
